### ISSUE TITLE
Consider emacs-helm organisation

### ISSUE THREAD

**Issue by manuel-uberti** [manuel-uberti/helm-wordnut#1]
@thierryvolpiatto

Would you consider adding this to [emacs-helm](https://github.com/emacs-helm)? Is there anything required for this to be suitable for emacs-helm?

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> @thierryvolpiatto
>
> Would you consider adding this to emacs-helm?

Sure, I sent you an invitation, once you accept it you should have the
rights to add your package to emacs-helm (let me know if not) and push etc...

> Is there anything required for this to be suitable for emacs-helm?

For now not what I know.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Well, wow! I don't really know what to say, except thank you so much for this. :)

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> Well, wow! I don't really know what to say, except thank you so much for this. :)

Thanks to you, looks a great tool to improve my english :-)
Will try soon.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
I have installed and tried helm-wordnut, looks great, thanks.
I have submitted two small issues (that are not really issues :-)).

Manuel Uberti <notifications@github.com> writes:

> Well, wow! I don't really know what to say, except thank you so much for this. :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Great! Glad it's helpful for you too. :)
