### ISSUE TITLE
Use of dash perhaps unneeded

### ISSUE THREAD

**Issue by thierryvolpiatto** [manuel-uberti/helm-wordnut#2]
Using dash is not really needed most of the time, we have all in Emacs for free e.g.
I had to figure out what does `-interpose`, you can have the same with something like this:

```elisp
(-interpose " " helm-wordnut-cmd-options)
;; ==
(cl-loop for elm in helm-wordnut-cmd-options
         for count from 1
         if (cl-evenp count)
         collect " "
         else collect elm)
```

So here dash is required just for `-interpose`.
When there is too much use of dash, code becomes unreadable for the casual reader that haven't necessary learned dash (like me ;-)) like in e.g. magit.

**Comment by thierryvolpiatto** [comment]
Above is wrong, this should be better:

```elisp
(defun helm-interpose (sep seq)
  (cl-loop for elm in seq
           append (list sep elm) into lst
           finally return (cdr lst)))
```

**Comment by thierryvolpiatto** [comment]
And this even better:

``` elisp
(apply #'concat (-interpose " " helm-wordnut-cmd-options))
;; ==
(mapconcat 'identity helm-wordnut-cmd-options " ")
```

**Comment by manuel-uberti** [comment]
Fantastic, thanks for the suggestion.
