### ISSUE TITLE
Shouldn't WordNet buffer be in outline-mode / org-mode?

### ISSUE THREAD

**Issue by Ambrevar** [manuel-uberti/helm-wordnut#4]
The current wordnet buffer seems to be rather barren in terms of fontification or bindings.

Switching to outline mode enables bindings (like jumping to next section) but fontification does not work (bug?).

With org-mode, everything works.

**Comment by manuel-uberti** [comment]
Thanks for reporting this.

I guess switching to org-mode should be fine. I'll work on it soon.
