### ISSUE TITLE
ivy interface, separate core feature.

### ISSUE THREAD

**Issue by thanhvg** [manuel-uberti/helm-wordnut#6]
Hi,

First of all thank you very much for this awesome package. It works very well with `helm`. However I don't think this package should be exclusive to `helm`. For example, it is very easy to define an `ivy` interface with the following code snippet:

``` elisp
(defun counsel-wordnut ()
  "Search wordnut with ivy."
  (interactive)
  (ivy-read "Wordnut search: "
            (helm-wordnut--get-candidates)
            :history 'counsel-wordnut-history
            :require-match t
            :action #'helm-wordnut--persistent-action
            :caller 'counsel-wordnut))
```

Can we separate the core feature into one el `wordnut-core.el` then we can implement `helm` and `ivy` interfaces in two other files `helm-wordnut` and `counsel-wordnut` respectively?

Thanks.

**Comment by manuel-uberti** [comment]
Hi,

thank you for your interest in this package. I don't use `ivy` so I wrote only the functionalities I need, but I am of course open to suggestions and pull requests.

Can you file a PR with the solution you have in mind?

**Comment by manuel-uberti** [comment]
Since I do not plan to work on this (as I said, it works with Helm and I am happy with that), I am going to close this issue. If you feel like developing a solution, feel free to open a PR and we can discuss it together.
